[nix_2_3]
paths = [
  # Ordering change after 2.3
  "eval-okay-xml",

  # In 2.3, even if NIX_PATH is overwritten,
  # nix search path includes `corepkgs` and test
  # assertion fails
  "eval-okay-search-path",

  # Nix changed how filterSource works,
  # so the output of latest Nix and others (Nix2.3, Lix) differs
  #
  # Related issue: https://github.com/NixOS/nix/issues/7761
  "filterSource-symlink-dir",

  # getAttrPos gains support for functionArgs-returned sets after 2.3
  "eval-okay-getattrpos-functionargs",

  # getAttrPos calculates columns differently in 2.3
  "eval-okay-inherit-attr-pos",

  # Newer Nix versions return an attr set, while 2.3 returns null
  "unsafeGetAttrPos-corepkgs",
]
builtins = ["readFileType"]
features = ["flakes", "pipe-operators", "path-interpolation"]

[lix_latest]
paths = [
  "filterSource-symlink-dir",

  # Newer Nix versions return an attr set, while Lix returns null
  "unsafeGetAttrPos-corepkgs",
]

[nix_latest]
