let
  attr-path = {foo.bar = 1;};

  lhs = {foo = 0;};
  rhs = {
    foo = 1;
    bar = 2;
  };
in [
  # For attr paths, the first segment is returned e.g
  # for `foo.bar` is must be the position of `foo`
  (builtins.unsafeGetAttrPos "bar" attr-path.foo)

  # intersectAttrs preserves position
  (builtins.unsafeGetAttrPos "foo" (builtins.intersectAttrs lhs rhs))

  # intersectAttrs returns RHS position
  (builtins.unsafeGetAttrPos "foo" (builtins.intersectAttrs {foo = 1;} {foo = 2;}))

  # update operator returns LHS position
  (builtins.unsafeGetAttrPos "foo" {foo = 1;} // {foo = 2;})

  # for attrsets generated by listToAttrs, the value's position is returned
  (builtins.unsafeGetAttrPos "foo" (builtins.listToAttrs [
    {
      name = "foo";
      value = 1;
    }
  ]))

  # Two cases below based on this commit:
  # https://github.com/NixOS/nix/commit/19ec1c9fd4d4bf6e941b046b8549ba2a1a690937
  #
  # Anonymous attrset
  (builtins.unsafeGetAttrPos "y" {y = "x";})

  # Attrset imported from another file
  (builtins.unsafeGetAttrPos "y" (import ./foo.nix))
]
